spring:
  application:
    name: crud-sql

  datasource:
    url: jdbc:mysql://localhost:3306/spring_crud_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true